name: Export Orna Lists

on:
  workflow_dispatch:   # only manual trigger

jobs:
  export-lists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Export itemlist.json and spelllist.json
        run: |
          python - <<'EOF'
          import json, pathlib

          # Load codex + i18n
          codex = json.load(open("data/codex.json", encoding="utf-8"))
          en = json.load(open("data/i18n/en.json", encoding="utf-8"))

          codex_items = codex.get("main", {}).get("items", {})
          codex_spells = codex.get("main", {}).get("spells", {})

          i18n_items = en.get("main", {}).get("items", {})
          i18n_spells = en.get("main", {}).get("spells", {})

          # Collect usable items (simple list of names)
          usable_item_names = sorted([
              i18n_items[item_id]["name"]
              for item_id, item in codex_items.items()
              if item.get("item_type") == "useable" and item_id in i18n_items
          ])

          # Collect all spells (simple list of names)
          spell_names = sorted([
              i18n_spells[spell_id]["name"]
              for spell_id in codex_spells.keys()
              if spell_id in i18n_spells
          ])

          pathlib.Path("data/itemlist.json").write_text(
              json.dumps(usable_item_names, indent=2, ensure_ascii=False),
              encoding="utf-8"
          )
          pathlib.Path("data/spelllist.json").write_text(
              json.dumps(spell_names, indent=2, ensure_ascii=False),
              encoding="utf-8"
          )
          EOF

      - name: Commit and push updated lists
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/itemlist.json data/spelllist.json
          git commit -m "Update itemlist + spelllist [ci skip]" || echo "No changes"
          git push
