name: Update Orna Items

on:
  schedule:
    - cron: "0 3 * * *"   # every day at 03:00 UTC
  workflow_dispatch:       # allow manual trigger from GitHub UI

jobs:
  crawl-items:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run items spider
        run: |
          mkdir -p data
          scrapy crawl items -o data/items.json -t json -s BOT_NAME=ornacodex

      - name: Commit and push updated items.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/items.json
          git commit -m "Update items.json [ci skip]" || echo "No changes"
          git push
