name: Update Orna Items

on:
  workflow_dispatch:       # allow manual trigger from GitHub UI

jobs:
  crawl-items:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler (download + codex)
        run: |
          mkdir -p data
          python main.py download --tmp tmp
          python main.py codex --tmp tmp --output data

      - name: Commit and push updated data
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Update codex JSON [ci skip]" || echo "No changes"
          git push
